[[ships]]
"Architectural Code" = "CP"
"Model Code" = 82
"Model Changes" = 3
"Ship Subtype" = "Vessel"
"class" = "Scouting"
"C2S ABC Classification" = "A"
"owner" = "Pan"
"Ship Name" = "Capybara"
"Participant?" = 1