[[ships]]
"Architectural Code" = "CT"
"Model Code" = "FH"
"Model Changes" = 9
"Ship Subtype" = "Interceptor"
"unnamed_field_3" = "Unmanned"
"C2S ABC Classification" = "A"
"owner" = "Suya"
"Ship Name" = "Catfish"
"Participant?" = 1