name: Trigger Deploy from Main

on:
    push:
        branches:
        - main
        paths:
        - 'content/**'
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    run-deploy:
        uses: ./.github/workflows/deploy.yml
