name: Trigger Deploy from Quartz Engine

on:
  push:
    branches:
      - quartz-test # currently use the `quartz-test` branch
  workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
  run-deploy:
    uses: ./.github/workflows/deploy.yml
